include: package:lint/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  errors:
    missing_return: error
    missing_required_param: error
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    sort_unnamed_constructors_first: false
