name: drinq
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_hooks: any
  state_notifier: any
  hooks_riverpod: 0.6.0-dev+2
  freezed_annotation: any
  uuid: any
  localstorage: any
  flutter_secure_storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  build_runner: any
  nitpicky:
    git:
      url: https://github.com/VGVentures/nitpicky
      ref: 1.0.2

flutter:
  uses-material-design: true
